### ISSUE TITLE
Highradius Source Code Data Leakage | Action Needed ASAP

### ISSUE THREAD

**Issue by Ranjit-Chigurupati** [Siddp278/Highradius_internship#1]
Hi Siddp278,

We identified that one of your GitHub public Repositories “[Highradius_internship](https://github.com/Siddp278/Highradius_internship)” contains a source code which is related/owned by the Highradius. Please Delete/remove the respective data from the public exposure, if not this will be considered as a Copyright Violation and necessary action will be taken.

Any data that is related/owned by the Highradius Corporation should not be used for your personal benefits or should not exposed in to the public. Any such unauthorized activities will be considered as series offence and necessary legal actions will be taken.

Regards,
Ranjit.

**Comment by Siddp278** [comment]
I see, yeah I will do the needful.
